job: extension
config:
  name: clasp_lora
  process:
    - type: sd_trainer
      training_folder: /data/kyana-images/output_sdxl
      device: cuda:0
      trigger_word: "<claspX>"
      
      network:
        type: lora
        linear: 32
        linear_alpha: 32
      
      save:
        dtype: float16
        save_every: 500
        max_step_saves_to_keep: 7
      
      datasets:
        - folder_path: /data/kyana-images/datasets/clasp
          caption_ext: txt
          caption_dropout_rate: 0.03
          shuffle_tokens: false
          resolution: [1024, 1024]
      
      train:
        batch_size: 1
        steps: 3500
        gradient_accumulation: 4
        train_unet: true
        train_text_encoder: true
        gradient_checkpointing: true
        optimizer: adamw
        lr: 1e-4
        text_encoder_lr: 5e-5
        lr_scheduler: cosine
        optimizer_params:
          weight_decay: 5e-5
        dtype: fp16
        cache_text_embeddings: true
      
      model:
        name_or_path: "stabilityai/stable-diffusion-xl-base-1.0"
      
      sample:
        sampler: euler
        sample_every: 500
        width: 1024
        height: 1024
        prompts:
          - "<claspX> kya-na watch strap clasp closing position, buckle mechanism securing, textured strap with metal attachments, six small flexible sensors visible underneath strap from ring edge, fastening system detail, black metallic matte finish, professional product photography, white background"
          - "<claspX> kya-na watch strap clasp open position, buckle mechanism unsecured, textured strap with metal attachments, six small flexible sensors visible underneath strap from ring edge, fastening system detail, black metallic matte finish, professional product photography, white background"
          - "<claspX> kya-na watch clasp mechanism detail closeup, secure fastening system, buckle closure design, metal clasp components, precision engineering, black metallic matte finish, professional product photography, white background"
          - "<claspX> kya-na watch strap clasp mechanism, secure fastening system detail, textured silicon strap material, metal strap attachments visible, six small flexible sensors underneath each strap from ring edge, buckle closure design, professional product photography, white background"
        neg: "low quality, blurry, distorted, watermark, text, wrong product, generic smartwatch, incorrect sensor count, misaligned parts, floating components, hallucinated features, wrong clasp design, incorrect fastening mechanism"
        seed: 42
        walk_seed: true
        guidance_scale: 7.0
        sample_steps: 50

meta:
  name: "Kya-na Clasp SDXL LoRA"
  version: '1.0'
  description: "SDXL LoRA for kya-na health watch clasp mechanism - focuses on buckle fastening system, open/closed states, and clasp engineering details"

