job: extension
config:
  name: ring_frame_lora
  process:
    - type: sd_trainer
      training_folder: /data/kyana-images/output_sdxl
      device: cuda:0
      trigger_word: "<ringX>"
      
      network:
        type: lora
        linear: 32
        linear_alpha: 32
      
      save:
        dtype: float16
        save_every: 500
        max_step_saves_to_keep: 7
      
      datasets:
        - folder_path: /data/kyana-images/datasets/ring_frame
          caption_ext: txt
          caption_dropout_rate: 0.03
          shuffle_tokens: false
          resolution: [1024, 1024]
      
      train:
        batch_size: 1
        steps: 3500
        gradient_accumulation: 4
        train_unet: true
        train_text_encoder: false                                                                                                                                                        mmkkkk
        gradient_checkpointing: true
        optimizer: adamw
        lr: 1e-4
        lr_scheduler: cosine
        optimizer_params:
          weight_decay: 5e-5
        dtype: fp16
        cache_text_embeddings: true
      
      model:
        name_or_path: "stabilityai/stable-diffusion-xl-base-1.0"
      
      sample:
        sampler: euler
        sample_every: 500
        width: 1024
        height: 1024
        prompts:
          - "<ringX> kya-na watch ring frame, outer ring structure, six copper connector pins on top edge, golden metallic contact pins, pins arranged on left, right, and middle sections, precision electrical connection points, technical closeup, black metallic matte finish, professional product photography, white background"
          - "<ringX> kya-na watch ring frame with magnetic connectors, mounting interface detail, precision connection system, magnetic attachment mechanism visible, ring frame structure, black metallic matte finish, professional product photography, white background"
          - "<ringX> kya-na watch showing attachment of core device to ring frame, magnetic connection interface visible, six copper connector pins on ring frame top edge, pins arranged on left, right, and middle sections, ring frame outer structure, attachment logic demonstration, black metallic matte finish, professional product photography, white background"
          - "<ringX> kya-na watch ring frame detail, outer ring component, six connector pins on ring frame top edge, golden metallic contact pins, electrical connection interface, precision engineering, technical closeup, black metallic matte finish, professional product photography, white background"
        neg: "low quality, blurry, distorted, watermark, text, wrong product, generic smartwatch, incorrect pin count, misaligned parts, floating components, hallucinated features, wrong number of pins, incorrect pin arrangement, wrong connector type"
        seed: 42
        walk_seed: true
        guidance_scale: 7.0
        sample_steps: 50

meta:
  name: "Kya-na Ring Frame SDXL LoRA"
  version: '1.0'
  description: "SDXL LoRA for kya-na health watch ring frame - focuses on outer ring frame structure, copper connector pins, magnetic connectors, and attachment interface mechanisms"

