job: extension
config:
  name: strap_lora
  process:
    - type: sd_trainer
      training_folder: /data/kyana-images/output_sdxl
      device: cuda:0
      trigger_word: "<strapX>"
      
      network:
        type: lora
        linear: 32
        linear_alpha: 32
      
      save:
        dtype: float16
        save_every: 500
        max_step_saves_to_keep: 7
      
      datasets:
        - folder_path: /data/kyana-images/datasets/strap
          caption_ext: txt
          caption_dropout_rate: 0.03
          shuffle_tokens: false
          resolution: [1024, 1024]
      
      train:
        batch_size: 1
        steps: 3500
        gradient_accumulation: 4
        train_unet: true
        train_text_encoder: false
        gradient_checkpointing: true
        optimizer: adamw
        lr: 1e-4
        lr_scheduler: cosine
        optimizer_params:
          weight_decay: 5e-5
        dtype: fp16
        cache_text_embeddings: true
      
      model:
        name_or_path: "stabilityai/stable-diffusion-xl-base-1.0"
      
      sample:
        sampler: euler
        sample_every: 500
        width: 1024
        height: 1024
        prompts:
          - "<strapX> kya-na watch ring frame with textured strap, flat configuration, six small flexible sensors underneath each strap from ring edge, metal strap attachments visible, black metallic matte finish, professional product photography, white background"
          - "<strapX> kya-na watch with textured strap, bottom view showing sensor array, chrome rounded glass biometric sensors, metal strap attachments connecting to ring, six small flexible sensors underneath each strap from ring edge, black metallic matte finish, professional product photography, white background"
          - "<strapX> kya-na watch ring frame detail, strap in circular configuration, six small flexible sensors underneath each strap from ring edge, metal strap attachments, black metallic matte finish, professional product photography, white background"
          - "<strapX> kya-na watch strap with sensors active, six small flexible sensors underneath each strap from ring edge, sensors with LED indicators visible, metal strap attachments, black metallic matte finish, professional product photography, white background"
        neg: "low quality, blurry, distorted, watermark, text, wrong product, generic smartwatch, incorrect sensor count, misaligned parts, floating components, hallucinated features, wrong number of sensors, leather strap, fabric strap, incorrect strap material"
        seed: 42
        walk_seed: true
        guidance_scale: 7.0
        sample_steps: 50

meta:
  name: "Kya-na Strap SDXL LoRA"
  version: '1.0'
  description: "SDXL LoRA for kya-na health watch strap and ring frame components - focuses on strap configurations, sensor arrays, and ring frame details"

